defmodule Advent.Puzzles do
  @moduledoc """
  AUTO-GENERATED BY `mix advent.gen`
  """

  @puzzles [
    Advent.Day01,
    Advent.Day02,
    Advent.Day03,
    Advent.Day04,
    Advent.Day05,
    Advent.Day06,
    Advent.Day07,
    Advent.Day08
  ]

  def all, do: @puzzles
end
