defmodule Advent.Puzzles do
  @moduledoc """
  AUTO-GENERATED BY `mix advent.gen`
  """

  @puzzles [
    Advent.Day01,
    Advent.Day02,
    Advent.Day03,
    Advent.Day04,
    Advent.Day05,
    Advent.Day06,
    Advent.Day07,
    Advent.Day08,
    Advent.Day09,
    Advent.Day10,
    Advent.Day11,
    Advent.Day12,
    Advent.Day13,
    Advent.Day14,
    Advent.Day15
  ]

  def all, do: @puzzles
end
